/* ══════════════════════════════════════════════════════════════════════════
   ESCUELITA · MEDIOS DE PAGO — Datos de referencia (ground truth)
   GENERADO automaticamente. No editar a mano.

   Fuentes:
     · Diccionario Autorizacion 12.06.xlsx  -> 20 sub-tablas / 544 registros
     · Manual de iniciativas macro.xlsx     -> 116 iniciativas / 30 conceptos

   Formato: filas como tuplas (sin repetir claves) + encabezado una vez por
   seccion. El indice de lookup se construye una sola vez al importar.
   ══════════════════════════════════════════════════════════════════════════ */

/** Sub-tabla del diccionario. `hdr` nombra las columnas de cada fila de `rows`. */
export type Seccion = {
  sheet: string;
  sec: string;
  desc: string;
  pri: "Alta" | "Media" | "Baja";
  hdr: string[];
  rows: string[][];
};

/** Iniciativa historica: [concepto, nombre, descripcion/pasos]. */
export type Iniciativa = [string, string, string];

export const SECCIONES: Seccion[] = [
  {
    sheet: "CodResVisa", sec: "Authorization Response Category", pri: "Alta",
    desc: "Clasificación del resultado de la autorización que agrupa los códigos de respuesta (Field 39) en categorías como aprobación, rechazo por cliente, error técnico o seguridad.",
    hdr: ["Código de respuesta", "Descripción", "Detalle", "Categoría"],
    rows: [
      ["0", "Transacción aprobada", "Transacción aprobada", "Aprobado"],
      ["5", "No aprobar (Do not honor)", "El emisor rechaza la transacción sin detallar motivo específico. Generalmente implica riesgo, bloqueo o decisión interna.", "4"],
      ["6", "Error general", "Error general del sistema o procesamiento. Puede estar asociado a fallas técnicas o inconsistencias en la transacción.", "4"],
      ["7", "Retener tarjeta – fraude", "Tarjeta vinculada a fraude. Se indica retenerla. Alto riesgo, no reintentar.", "1"],
      ["10", "Aprobación parcial", "La transacción se aprueba parcialmente por un monto menor al solicitado.", "Aprobado"],
      ["11", "Aprobado VIP (se convierte a 00)", "Aprobación especial para clientes VIP. Internamente se trata como aprobación normal.", "Aprobado"],
      ["12", "Transacción inválida", "La transacción es inválida por formato, tipo o reglas no permitidas.", "1"],
      ["13", "Monto inválido", "El monto es inválido o hay error en conversión de moneda.", "4"],
      ["14", "Cuenta inválida", "El número de cuenta no existe, tiene formato incorrecto o no pasa validaciones.", "1"],
      ["15", "Emisor no existe", "El BIN no corresponde a un emisor válido.", "1"],
      ["19", "Reintentar transacción", "Se solicita reingresar la transacción, normalmente por error temporal.", "2"],
      ["21", "Sin acción tomada", "No se realizó ninguna acción; sin impacto en la cuenta.", "No aplicable"],
      ["25", "Registro no encontrado", "No se encuentra el registro en el sistema del emisor.", "No aplicable"],
      ["28", "Archivo no disponible", "Sistema disponible parcialmente; no se puede consultar o actualizar.", "No aplicable"],
      ["39", "No existe cuenta de crédito", "No existe cuenta de crédito asociada.", "2"],
      ["41", "Tarjeta perdida", "Tarjeta reportada como perdida. Se debe retener.", "1"],
      ["43", "Tarjeta robada", "Tarjeta reportada como robada. Riesgo alto.", "1"],
      ["46", "Cuenta cerrada", "Cuenta cerrada, no puede operar.", "1"],
      ["51", "Fondos insuficientes", "Fondos insuficientes para cubrir el monto.", "2"],
      ["52", "No existe cuenta corriente", "No existe cuenta corriente asociada.", "2"],
      ["53", "No existe cuenta de ahorros", "No existe cuenta de ahorros asociada.", "2"],
      ["54", "Tarjeta vencida", "Tarjeta expirada o fecha inválida.", "3"],
      ["55", "PIN incorrecto", "PIN incorrecto o faltante.", "3"],
      ["57", "Transacción no permitida al cliente", "El cliente no tiene permitido realizar este tipo de operación.", "No aplicable"],
      ["58", "Transacción no permitida en terminal", "El terminal no permite ese tipo de transacción.", "4"],
      ["59", "Sospecha de fraude", "Transacción sospechosa de fraude.", "2"],
      ["61", "Excede límite", "Se excede el monto máximo autorizado.", "2"],
      ["62", "Tarjeta restringida", "Tarjeta restringida por ubicación o condiciones.", "2"],
      ["63", "Violación de seguridad", "Problema de seguridad o emisor incorrecto.", "No aplicable"],
      ["64", "No cumple AML", "No cumple con regulaciones contra lavado de dinero.", "4"],
      ["65", "Excede frecuencia", "Se excedió la frecuencia permitida de retiros.", "2"],
      ["70", "PIN requerido", "Se requiere ingreso de PIN.", "3"],
      ["74", "Error en PIN (criptografía)", "Error en cifrado o valor del PIN.", "4"],
      ["75", "Intentos PIN excedidos", "Se excedió el número de intentos de PIN.", "2"],
      ["76", "Reversa sin original", "Reverso sin transacción original asociada.", "No aplicable"],
      ["78", "Tarjeta bloqueada/no activada", "Tarjeta bloqueada o no activada.", "2"],
      ["79", "Reversada por switch", "Transacción revertida por el switch.", "4"],
      ["80", "Sin impacto financiero", "No hay impacto financiero (ej. reverso de rechazo).", "4"],
      ["81", "Error criptográfico PIN", "Error criptográfico en validación de PIN.", "4"],
      ["82", "Error CVV/CAVV", "Fallo en verificación de seguridad (CVV u otros).", "3"],
      ["85", "Sin razón para rechazar verificación", "No hay motivo para rechazar validaciones como CVV o dirección.", "No aplicable"],
      ["86", "No se puede verificar PIN", "No se puede validar el PIN (ej. falta PVV).", "2"],
      ["91", "Emisor no disponible", "Emisor no disponible o sin respuesta (timeout o caída).", "2"],
      ["92", "No se puede enrutar", "No se puede enrutar la transacción correctamente.", "No aplicable"],
      ["93", "Violación de ley", "Rechazo por incumplimiento legal o regulatorio.", "2"],
      ["94", "Duplicado", "Transacción duplicada detectada.", "No aplicable"],
      ["96", "Falla de sistema", "Error general del sistema o procesamiento.", "2"],
      ["1A", "Autenticación adicional requerida", "Se requiere autenticación adicional (ej. 3DS).", "3"],
      ["5C", "Transacción no soportada", "Transacción no soportada o bloqueada por el emisor.", "2"],
      ["6P", "Fallo en verificación", "Fallo en datos de verificación.", "3"],
      ["9G", "Bloqueado por titular", "Bloqueada por el cliente, requiere contacto.", "2"],
      ["B1", "Recargo no permitido", "Recargo no permitido (caso específico EE. UU.).", "No aplicable"],
      ["N0", "Forzar STIP", "El emisor fuerza procesamiento en STIP.", "4"],
      ["N3", "Efectivo no disponible", "Servicio de efectivo no disponible.", "2"],
      ["N4", "Excede límite de retiro", "Monto de retiro excede límite permitido.", "2"],
      ["N7", "Fallo CVV2", "Fallo en validación de CVV2.", "3"],
      ["N8", "Excede monto preautorizado", "Monto supera el previamente autorizado.", "No aplicable"],
      ["P5", "Desbloqueo PIN denegado", "Solicitud de desbloqueo de PIN rechazada.", "No aplicable"],
      ["P6", "Cambio PIN denegado", "Cambio de PIN rechazado (no seguro).", "No aplicable"],
      ["Q1", "Fallo autenticación", "Fallo en autenticación de tarjeta o PIN offline.", "No aplicable"],
      ["R0", "Detener pago", "Orden de detener un pago específico.", "1"],
      ["R1", "Detener pagos futuros", "Orden de detener pagos recurrentes.", "1"],
      ["R2", "No califica para PIN", "Transacción no califica para PIN.", "No aplicable"],
      ["R3", "Detener comercios", "Bloqueo total de comercios.", "1"],
      ["Z3", "Offline rechazado", "No se puede ir online; transacción rechazada offline.", "4"],
      ["Z5", "Monto no soportado", "Cuenta válida pero monto no permitido.", "No aplicable"],
      ["Z6", "MCC inválido", "Código MCC incorrecto; requiere corrección.", "No aplicable"],
    ],
  },
  {
    sheet: "CodResVisa", sec: "Category", pri: "Alta",
    desc: "",
    hdr: ["categoría", "Authorization Response Category", "descripción"],
    rows: [
      ["1", "Critical / Pick-up / Fraud", "Transacciones críticas asociadas a fraude, tarjetas comprometidas, cuentas inválidas o bloqueos severos. No permiten reintento y suelen requerir acción inmediata."],
      ["2", "Decline", "Transacciones rechazadas por condiciones del cliente o límites, como fondos insuficientes, restricciones o límites excedidos. Puede permitirse reintento según el caso."],
      ["3", "Security / Verification", "Rechazos por problemas de autenticación o verificación, como PIN incorrecto, CVV fallido, autenticación adicional requerida o tarjeta expirada."],
      ["4", "Error / Processing", "Rechazos por errores técnicos, de sistema o validación, como fallas de red, errores operativos o malformación de datos."],
      ["Aprobación", "Approval", "Transacciones aprobadas total o parcialmente, incluyendo aprobación estándar, parcial o VIP."],
      ["No aplicable", "Not applicable", "Casos administrativos, informativos o técnicos donde no aplica una categorización de autorización directa."],
    ],
  },
  {
    sheet: "CodResVisa", sec: "CYBS", pri: "Alta",
    desc: "",
    hdr: ["Value", "Content of Sub-Element", "Descripción"],
    rows: [
      ["1", "CYBS DM Result", "Aceptado por el Decision Manager de CyberSource según las reglas configuradas por el comercio."],
      ["2", "CYBS DM Result", "Enviado a revisión manual por el Decision Manager según las reglas del comercio."],
    ],
  },
  {
    sheet: "STIP", sec: "STIP code", pri: "Alta",
    desc: "Código que indica la razón por la cual Visa o el switch procesó una transacción en modo Stand-In (STIP), especificando causas como indisponibilidad del emisor, reglas, fraude o errores.",
    hdr: ["STIP code", "descripción"],
    rows: [
      ["9001", "The issuer is signed off."],
      ["9002", "The issuer was signed off by the switch."],
      ["9011", "The line to issuer is down."],
      ["9012", "Forced STIP because of N0 (Force STIP) original response from issuer."],
      ["9020", "The response from issuer timed out."],
      ["9021", "Alternate PCR used for Auth Destination."],
      ["9022", "PACM-diverted."],
      ["9024", "Transaction declined due to Visa Payment Controls (VPC) rule."],
      ["9025", "Declined by Selective Acceptance Service."],
      ["9026", "Transaction reviewed by the Visa Transaction Advisor Service: additional authentication required."],
      ["9027", "Declined by token provisioning service."],
      ["9030", "Based on the issuer response, account listed or updated in ASAF (Auto-CDB / Downgrade)."],
      ["9031", "Original processed in stand-in."],
      ["9033", "Declined due to active account management threshold exceeded."],
      ["9034", "Unable to deliver response to originator."],
      ["9035", "Process recurring payment in STIP."],
      ["9037", "Declined by Visa CTC (Consumer Transaction Controls)."],
      ["9038", "Merchandise return authorization processed in STIP."],
      ["9039", "VFC decline due to limited acceptance merchant."],
      ["9041", "PIN verification error."],
      ["9042", "Offline PIN authentication interrupted."],
      ["9045", "Switch unable to translate PIN."],
      ["9047", "Declined by Real-Time Decisioning (RTD)."],
      ["9048", "Invalid CVV with All Respond option."],
      ["9049", "Account verification – Visa Verify Only."],
      ["9054", "Invalid CAM."],
      ["9055", "Merchant program identifier missing."],
      ["9057", "STIP approved by Real-Time Decisioning (RTD)."],
      ["9058", "Approved by VFC Managed Transaction Decline Safeguard."],
      ["9063", "Transaction declined: processing requirements not met under regulated conditions (linked to Field 39 = 96)."],
      ["9064", "Transaction declined: invalid payment channel for card type."],
      ["9091", "Dispute financial."],
      ["9095", "Issuer notification of token vault provisioning or status change."],
      ["9028", "Issuer requested CDB update through GCAS."],
      ["9050", "Source or destination does not participate in service."],
      ["9070", "Declined by Account Screen; issuer participates in All Respond."],
      ["9061", "Internal system error or switch-detected error condition."],
      ["9102", "Switch generated reversal advice due to undelivered approval (0420)."],
      ["9103", "Approval not delivered due to issuer timeout (reversal generated)."],
      ["9200", "AA Score Request processed automatically by STIP (Visa internal use)."],
      ["9201", "Decline due to Visa Stop Payment Service (VSPS)."],
      ["9202", "Decline due to issuer country exclusion list."],
      ["9203", "Decline due to OFAC embargo."],
      ["9204", "Cashback processing error."],
      ["9205", "Invalid CAVV with decline option."],
      ["9206", "Mod-10 check failure."],
      ["9207", "Issuer does not support gambling transactions."],
      ["9208", "Declined: issuing/routing/token range blocked."],
      ["9209", "Declined: issuer does not support transaction type."],
      ["9210", "Declined due to issuer participation options."],
      ["9211", "Declined: acquirer does not support requested service."],
      ["9212", "Declined due to fraud condition."],
      ["9213", "Declined: external service call timeout."],
      ["9214", "Declined: error from external service call."],
      ["9215", "Declined: issuer blocked specific POS entry mode."],
      ["9216", "Non device-based token used to personalize."],
      ["9217", "Invalid tokenization data or format error."],
      ["9218", "Inconsistency between product subtype and business application identifier."],
      ["9219", "Merchant Blocking Service decline."],
      ["9220", "Device binding request failed."],
      ["9221", "Declined due to PFD acquirer-specific block."],
      ["9222", "Declined due to PFD issuer-specific block."],
      ["9223", "Declined due to client-tailored block (acquirer/merchant)."],
      ["9224", "Declined due to client-tailored block (issuer)."],
      ["9225", "Declined due to ecosystem PFD fraud block (general)."],
      ["9226", "Declined due to PFD block for other risk factors."],
      ["9227", "dCVV2 validation failed."],
      ["9229", "Declined due to domestic regulations."],
      ["9230", "RAM Fraud Rule decline (Visa internal use)."],
      ["9258", "Declined by VFC Managed Transaction Decline Safeguard."],
      ["9302", "Exceeds issuer settlement risk exposure cap."],
      ["9303", "Exceeds acquirer settlement risk exposure cap."],
      ["9999", "Authorization provision environment mismatch."],
    ],
  },
  {
    sheet: "Account Fonding", sec: "Account Funding Source", pri: "Baja",
    desc: "Tipo de cuenta o producto desde el cual se originan los fondos en una transacción (ej. Debit, Credit, Prepaid, Charge, Deferred Debit).",
    hdr: ["Product", "Account Funding Source", "Domestic", "International"],
    rows: [
      ["Consumer Debit", "D (Debit)", "Yes", "Yes"],
      ["Consumer Prepaid", "P (Prepaid)", "Yes", "Yes"],
      ["Consumer Credit", "C (Credit)", "Yes", "No"],
      ["Business Debit", "D (Debit)", "Yes", "Yes"],
      ["Business Prepaid", "P (Prepaid)", "Yes", "Yes"],
      ["Business Credit", "C (Credit)", "No", "Yes"],
      ["All Corporate and Purchasing Debit", "D (Debit)", "No", "Yes"],
      ["All Corporate and Purchasing Prepaid", "P (Prepaid)", "Yes", "Yes"],
      ["All Corporate and Purchasing Credit", "C (Credit)", "Yes", "No"],
      ["All Products Charge", "H (Charge)", "No", "No"],
      ["Deferred Debit", "R (Deferred Debit)", "No", "No"],
    ],
  },
  {
    sheet: "Procesing Code", sec: "Processing Transaction", pri: "Media",
    desc: "Tipo de operación que se está realizando en la transacción, definido por las posiciones 1–2 del Field 3 (ej. compra, retiro, transferencia, devolución).",
    hdr: ["Code", "Processing Transaction", "descripcion"],
    rows: [
      ["0", "Purchase (Goods/Services POS)", "Compra de bienes o servicios en punto de venta (transacción estándar)."],
      ["1", "Cash Disbursement", "Retiro de efectivo o adelanto de efectivo desde cuenta del cliente."],
      ["10", "Account Funding", "Transacción de fondeo de cuenta para cargar fondos."],
      ["11", "Quasi-Cash / Gambling", "Transacciones tipo efectivo (ej. apuestas, juegos, criptomonedas)."],
      ["20", "Return / Credit Voucher", "Devolución de bienes o emisión de crédito al cliente."],
      ["26", "Original Credit Transaction", "Transferencia de fondos hacia el cliente (pago o envío de dinero)."],
      ["28", "Load / Activation & Load", "Carga de tarjeta o activación con carga de fondos."],
      ["30", "Balance Inquiry", "Consulta de saldo o fondos disponibles."],
      ["34", "ATM Mini Statement", "Consulta de movimientos o mini estado de cuenta en ATM."],
      ["38", "Fee Inquiry", "Consulta de comisiones o cargos aplicables."],
      ["39", "Eligibility Inquiry", "Consulta de elegibilidad de productos o beneficios."],
      ["40", "Account Transfer (ATM)", "Transferencia de fondos entre cuentas en ATM."],
      ["50", "Bill Payment (US)", "Pago de servicios o facturas (solo EE.UU.)."],
      ["53", "Payment (US)", "Pago hacia el emisor (movimiento inverso al consumo)."],
      ["70", "PIN Change", "Cambio de PIN en ATM."],
      ["72", "PIN Unblock / Activation", "Desbloqueo de PIN o activación de tarjeta."],
    ],
  },
  {
    sheet: "Procesing Code", sec: "Account Type From", pri: "Media",
    desc: "",
    hdr: ["Code", "Account Type From", "Descripción"],
    rows: [
      ["0", "Not specified", "No se especifica cuenta"],
      ["10", "Savings", "Cuenta de ahorros"],
      ["20", "Checking", "Cuenta corriente"],
      ["30", "Credit", "Cuenta de tarjeta de crédito"],
      ["35", "Deferred debit", "Débito diferido"],
      ["36", "Charge", "Cuenta tipo charge"],
      ["40", "Universal", "Cuenta genérica/universal"],
      ["60", "Prepaid", "Cuenta prepago"],
      ["70", "Employee benefit", "Cuenta de beneficios"],
    ],
  },
  {
    sheet: "Procesing Code", sec: "Account Type (To)", pri: "Media",
    desc: "",
    hdr: ["Code", "Account Type To", "Descripción"],
    rows: [
      ["0", "Not applicable", "No aplica"],
      ["10", "Savings", "Cuenta de ahorros"],
      ["20", "Checking", "Cuenta corriente"],
      ["30", "Credit", "Cuenta de crédito"],
      ["40", "Universal", "Cuenta universal"],
    ],
  },
  {
    sheet: "Procesing Code", sec: "Transaction Usage Rules", pri: "Media",
    desc: "",
    hdr: ["Condición", "Regla"],
    rows: [
      ["ATM (MCC 6011)", "Debe usar Transaction Type = 01"],
      ["Cash disbursement (6010)", "Debe usar 01"],
      ["Gambling (7801 / 7802)", "Debe usar 11"],
      ["Cashback", "Debe usar 00"],
      ["Bill payment", "Debe usar 50"],
      ["Payment", "Debe usar 53"],
      ["Original Credit", "Debe usar 26"],
      ["Account Funding", "Debe usar 10"],
      ["Fee inquiry", "Debe usar 38"],
      ["Eligibility", "Debe usar 39"],
    ],
  },
  {
    sheet: "MOTO", sec: "ECI/MOTO", pri: "Media",
    desc: "Indicador del tipo de transacción en canales no presenciales o comercio electrónico, incluyendo comercio electrónico, mail order o telephone order.",
    hdr: ["Cod ECI/MOTO", "ECI/MOTO", "Descripción ECI"],
    rows: [
      ["0", "No aplicable", "Indica que el indicador de comercio electrónico, orden por correo o teléfono no es relevante para la transacción"],
      ["1", "Mail/Phone Order (única)", "Transacción única por correo/teléfono; no es recurrente ni en cuotas"],
      ["2", "Recurrente", "Indica transacción recurrente (principalmente para adquirentes US; otras regiones usan Field 126.13 = R)"],
      ["3", "Cuotas (Installment)", "Compra en múltiples pagos acordados entre cliente y comercio (otras regiones usan Field 126.13 = I)"],
      ["4", "Clasificación desconocida", "Tipo de orden por correo/teléfono desconocido"],
      ["5", "eCommerce seguro (3DS)", "Transacción autenticada usando protocolo aprobado (ej. 3-D Secure)"],
      ["6", "Intento 3DS no autenticado", "Se intentó autenticar con 3DS, pero no se completó (emisor o cliente no participa)"],
      ["7", "eCommerce no autenticado", "Transacción con cifrado de datos pero sin autenticación 3DS"],
      ["8", "eCommerce no seguro", "Transacción sin protección de datos"],
      ["9", "Reservado", "Valor reservado, no usar en autorizaciones"],
    ],
  },
  {
    sheet: "MOTO", sec: "ECI/CAVV", pri: "Media",
    desc: "",
    hdr: ["ECI", "CAVV válido", "Interpretación"],
    rows: [
      ["5", "Sí", "Baja probabilidad de fraude"],
      ["6", "Sí", "Riesgo medio (intento)"],
      ["7", "Sí", "Riesgo mayor (sin auth fuerte)"],
      ["7", "No", "Alto riesgo"],
    ],
  },
  {
    sheet: "CVV2", sec: "CVV2 Data Presence Code", pri: "Alta",
    desc: "Indicador que define si se envió o no el valor CVV2 y si la validación fue estática o dinámica (Field 126.10, posición 1).",
    hdr: ["Cod response", "CVV2", "Descripcion"],
    rows: [
      ["M", "Match", "El CVV2/dCVV2 fue verificado correctamente y coincide con el valor esperado."],
      ["N", "No Match", "El CVV2/dCVV2 fue verificado pero no coincide con el valor esperado (posible riesgo o error de ingreso)."],
      ["P", "Not Performed", "La verificación de CVV2/dCVV2 no se realizó, ya sea por configuración, rechazo previo o procesamiento en STIP."],
      ["S", "System Error", "Error del sistema durante la verificación; generalmente permite reintento."],
      ["U", "Unable to Verify", "No se pudo verificar el CVV2/dCVV2 porque el emisor no participa, faltan datos o no se tienen claves de validación."],
    ],
  },
  {
    sheet: "CVV2", sec: "CVV2 Authorization Request Data", pri: "Alta",
    desc: "",
    hdr: ["Field 126.10", "Tipo real", "Field 44.10 interpreta"],
    rows: [
      ["1", "CVV2 (estático)", "Resultado de CVV2"],
      ["3", "dCVV2 (dinámico)", "Resultado de dCVV2"],
      ["4", "Fallback", "Son casos donde el emisor convive con ambos"],
      ["0", "No validación", "Puede no existir o ser irrelevante"],
    ],
  },
  {
    sheet: "CVV2", sec: "CAVV", pri: "Alta",
    desc: "Resultado de la validación de autenticación del tarjetahabiente en 3D Secure (Visa Secure), indicando si la autenticación fue exitosa, fallida o solo intentada.",
    hdr: ["cod CAVV", "CAVV", "descripcion"],
    rows: [
      ["(blank)", "Not present", "CAVV no presente o no verificado; el emisor no ha seleccionado verificación CAVV."],
      ["0", "CAVV not verified", "No se pudo verificar el CAVV o no se proporcionó cuando era requerido."],
      ["1", "CAVV failed authentication", "El CAVV falló en verificación de autenticación (3DS)."],
      ["2", "CAVV passed authentication", "El CAVV fue verificado correctamente en autenticación (transacción autenticada)."],
      ["3", "CAVV passed (attempt)", "Verificación exitosa en intento de autenticación (attempted authentication con clave del issuer)."],
      ["4", "CAVV failed (attempt)", "Falló la verificación en intento de autenticación con clave del issuer."],
      ["5", "Reserved", "No utilizado (reservado para uso futuro)."],
      ["6", "Not verified (issuer not participating)", "CAVV no verificado porque el emisor no participa en la verificación."],
      ["7", "CAVV failed (attempt - Visa)", "Fallo en intento de autenticación con clave de Visa (Attempts Service)."],
      ["8", "CAVV passed (attempt - Visa)", "Verificación exitosa en intento de autenticación con clave de Visa."],
      ["9", "CAVV failed (attempt - ACS unavailable)", "Fallo en intento de autenticación cuando el ACS del emisor no estaba disponible."],
      ["A", "CAVV passed (attempt - ACS unavailable)", "Verificación exitosa en intento de autenticación sin disponibilidad del ACS."],
      ["B", "CAVV passed no liability shift", "CAVV verificado correctamente pero sin cambio de responsabilidad (liability shift)."],
      ["C", "Not verified (attempt)", "Autenticación intentada pero no verificada (generado por Visa)."],
      ["D", "Not verified (authentication)", "Autenticación completa no verificada (generado por Visa)."],
    ],
  },
  {
    sheet: "CVV2", sec: "ECI/CAVV", pri: "Alta",
    desc: "",
    hdr: ["ECI", "CAVV válido", "Interpretación"],
    rows: [
      ["5", "Sí", "Baja probabilidad de fraude"],
      ["6", "Sí", "Riesgo medio (intento)"],
      ["7", "Sí", "Riesgo mayor (sin auth fuerte)"],
      ["7", "No", "Alto riesgo"],
    ],
  },
  {
    sheet: "Response source", sec: "Response Source", pri: "Alta",
    desc: "Identifica el origen de la decisión de la autorización (issuer, STIP o VisaNet), definido por el Field 44.1.",
    hdr: ["Cod Response Source", "Response Source", "Descripcion"],
    rows: [
      ["0", "ASAF / Auto-CDB Advice", "Indica una actualización de cuenta iniciada por GCAS o Auto-CDB (mantenimiento de archivo)."],
      ["1", "STIP (timeout / invalid data)", "Respuesta generada por STIP debido a timeout del switch o datos inválidos en la respuesta del issuer."],
      ["2", "STIP (low amount / verification)", "Respuesta generada por STIP porque el monto está bajo el límite permitido o por solicitudes de verificación."],
      ["4", "STIP (issuer unavailable)", "STIP responde porque el emisor no estaba disponible para procesar la transacción."],
      ["5", "Issuer", "La respuesta fue generada directamente por el emisor."],
      ["7", "Reversal match", "El reverso fue correctamente asociado a la autorización original."],
      ["8", "Reversal no match", "No se encontró coincidencia con la autorización original para el reverso."],
      ["A", "Automated Fuel Dispenser", "Relacionado con transacciones o avisos de dispensadores de combustible automáticos (AFD)."],
      ["B", "STIP (Transaction Advisor)", "STIP respondió porque la transacción cumple criterios del Visa Transaction Advisor Service."],
      ["C", "STIP (other conditions)", "Respuesta generada por STIP por condiciones no especificadas en otros códigos."],
      ["H", "Exposure cap exceeded", "Se excedió el límite de exposición de riesgo del adquirente."],
      ["V", "VisaNet (issuer or STIP)", "La autorización fue procesada por VisaNet (puede provenir del issuer o STIP)."],
      ["^", "Not present", "El campo no está presente (valor en blanco)."],
    ],
  },
  {
    sheet: "POS", sec: "POS Condition", pri: "Media",
    desc: "Condición bajo la cual ocurre la transacción en el punto de venta, como presencia del cliente, e-commerce o terminal no atendido (Field 25).",
    hdr: ["POS Condition Code", "Condition Code", "Des Condition Code"],
    rows: [
      ["0", "Normal transaction", "Transacción normal con tarjeta y tarjetahabiente presentes en el comercio (cara a cara)."],
      ["1", "Cardholder not present", "Tarjetahabiente no presente en la transacción."],
      ["2", "Unattended / ATM", "Transacción en terminal desatendido o ATM activado por el cliente, con PIN presente."],
      ["3", "Merchant suspicious", "Comercio sospecha que la transacción o la tarjeta puede ser fraudulenta."],
      ["5", "Cardholder present, card not present", "Tarjetahabiente presente pero tarjeta no presente (datos almacenados o ingresados)."],
      ["6", "Preauthorization", "Preautorización según reglas de procesamiento de Visa."],
      ["8", "Mail/Phone/Recurring", "Transacción por correo, teléfono, recurrente, anticipada o en cuotas."],
      ["11", "Suspected fraud", "Sospecha de fraude (sin uso específico adicional definido)."],
      ["12", "Security", "Condición de seguridad (sin uso específico adicional definido)."],
      ["51", "Verification request", "Solicitud de verificación (cuenta, CVV, dirección, elegibilidad) sin autorización financiera."],
      ["59", "E-commerce", "Transacción de comercio electrónico por red pública (Internet)."],
      ["71", "Key entered (mag stripe fail)", "Tarjeta presente pero banda no leída; datos ingresados manualmente."],
    ],
  },
  {
    sheet: "POS", sec: "POS Entry Mode", pri: "Media",
    desc: "Método técnico de captura de los datos de la tarjeta (chip, banda, manual, contactless, credential on file), definido en Field 22.",
    hdr: ["POS Entry Mode", "Entry Mode", "POS Entry Mode Rollup", "POS Entry Mode Rollup Derived"],
    rows: [
      ["0", "Unknown", "Unknown", "Unknown"],
      ["1", "Manual (key entry)", "Manual", "Card Not Present / Keyed"],
      ["2", "Magnetic stripe (no CVV guaranteed)", "Magnetic Stripe", "Card Present"],
      ["3", "Optical code", "Optical", "Card Present"],
      ["5", "Chip (contact ICC, VSDC)", "Chip", "Card Present (Secure)"],
      ["7", "Contactless (qVSDC)", "Contactless Chip", "Card Present (Contactless)"],
      ["10", "Credential on file", "Credential on File", "Card Not Present (Stored Credential)"],
      ["90", "Magnetic stripe (full track data)", "Magnetic Stripe Full", "Card Present"],
      ["91", "Contactless (MSD)", "Contactless MSD", "Card Present (Contactless)"],
      ["95", "Chip (ICC fallback or limited CVV)", "Chip", "Card Present (Fallback possible)"],
    ],
  },
  {
    sheet: "POS", sec: "POS Environment", pri: "Media",
    desc: "Tipo de relación entre cliente y comercio, como transacciones recurrentes, en cuotas o con credenciales almacenadas (Field 126.13).",
    hdr: ["POS Environment", "Environment", "Des Environment"],
    rows: [
      ["C", "Credential on File", "Indica credenciales guardadas. Se usa para almacenamiento inicial o para transacciones iniciadas por el comercio con credenciales ya almacenadas (unscheduled card-on-file)."],
      ["I", "Installment Payment", "Indica que la transacción corresponde a un pago en cuotas (instalment). Usado en transacciones posteriores de un plan de pagos."],
      ["R", "Recurring Payment", "Indica pagos recurrentes acordados entre cliente y comercio (ej. suscripciones, servicios periódicos)."],
    ],
  },
  {
    sheet: "MCC", sec: "MCC", pri: "Media",
    desc: "Código que identifica el tipo de comercio o actividad del merchant donde se realiza la transacción (Field 18).",
    hdr: ["COD", "MCC", "Descripcion"],
    rows: [
      ["742", "Veterinary Services", "Servicios veterinarios"],
      ["763", "Agricultural Co-operatives", "Servicios agrícolas"],
      ["780", "Landscaping", "Jardinería y paisajismo"],
      ["1520", "General Contractors", "Construcción general"],
      ["1711", "HVAC Contractors", "Climatización y plomería"],
      ["1731", "Electrical Contractors", "Servicios eléctricos"],
      ["1740", "Masonry", "Albañilería"],
      ["1750", "Carpentry", "Carpintería"],
      ["1761", "Roofing", "Techos"],
      ["1771", "Concrete", "Concreto"],
      ["1799", "Special Trades", "Construcción especializada"],
      ["2741", "Printing", "Impresión"],
      ["2791", "Typesetting", "Tipografía"],
      ["2842", "Cleaning Products", "Productos limpieza"],
      ["4011", "Railroads", "Transporte ferroviario carga"],
      ["4111", "Local Transport", "Transporte urbano"],
      ["4112", "Passenger Rail", "Tren pasajeros"],
      ["4119", "Ambulances", "Ambulancias"],
      ["4121", "Taxi", "Taxis"],
      ["4131", "Bus Lines", "Buses"],
      ["4214", "Trucking", "Transporte carga"],
      ["4215", "Courier", "Mensajería"],
      ["4225", "Warehousing", "Almacenaje"],
      ["4411", "Cruise Lines", "Cruceros"],
      ["4457", "Boat Rentals", "Alquiler botes"],
      ["4468", "Marinas", "Servicios marinos"],
      ["4511", "Airlines", "Aerolíneas"],
      ["4582", "Airports", "Aeropuertos"],
      ["4722", "Travel Agencies", "Turismo"],
      ["4784", "Tolls", "Peajes"],
      ["4789", "Transport Services", "Transporte varios"],
      ["4812", "Telecom Equipment", "Equipos telecom"],
      ["4814", "Telecom Services", "Servicios telecom"],
      ["4816", "Internet Services", "Internet"],
      ["4821", "Telegraph", "Telégrafo"],
      ["4829", "Money Transfer", "Transferencias"],
      ["4899", "Streaming", "TV / cable / streaming"],
      ["4900", "Utilities", "Servicios públicos"],
      ["5013", "Auto Parts Wholesale", "Repuestos autos"],
      ["5021", "Office Furniture", "Muebles oficina"],
      ["5039", "Construction Materials", "Materiales construcción"],
      ["5044", "Photographic Equip", "Equipos foto"],
      ["5045", "Computers", "Hardware/software"],
      ["5046", "Commercial Equip", "Equipos comerciales"],
      ["5047", "Medical Equipment", "Equipos médicos"],
      ["5051", "Metals", "Metales"],
      ["5065", "Electrical Equip", "Equipos eléctricos"],
      ["5072", "Hardware Wholesale", "Ferretería mayorista"],
      ["5074", "Plumbing Supplies", "Plomería"],
      ["5085", "Industrial Supplies", "Industrial"],
      ["5094", "Jewelry Wholesale", "Joyería mayorista"],
      ["5099", "Durable Goods", "Bienes durables"],
      ["5111", "Office Supplies", "Papelería"],
      ["5122", "Drugs Wholesale", "Medicamentos"],
      ["5131", "Textiles", "Telas"],
      ["5137", "Uniforms", "Uniformes"],
      ["5139", "Footwear", "Calzado"],
      ["5169", "Chemicals", "Químicos"],
      ["5172", "Petroleum", "Combustibles"],
      ["5192", "Books", "Libros"],
      ["5193", "Florist Supplies", "Flores"],
      ["5198", "Paint", "Pinturas"],
      ["5199", "Nondurable Goods", "Insumos varios"],
      ["5200", "Home Warehouse", "Retail hogar grande"],
      ["5211", "Lumber", "Materiales construcción"],
      ["5231", "Paint Stores", "Pinturas"],
      ["5251", "Hardware Stores", "Ferretería"],
      ["5261", "Garden Stores", "Jardinería"],
      ["5262", "Marketplaces", "Marketplace digital"],
      ["5271", "Mobile Homes", "Casas móviles"],
      ["5300", "Wholesale Clubs", "Clubes mayoristas"],
      ["5309", "Duty Free", "Duty free"],
      ["5310", "Discount Stores", "Descuento"],
      ["5311", "Department Stores", "Retail grande"],
      ["5331", "Variety Stores", "Tiendas económicas"],
      ["5399", "General Merchandise", "Retail general"],
      ["5411", "Grocery", "Supermercados"],
      ["5422", "Meat", "Carnicería"],
      ["5441", "Candy", "Dulces"],
      ["5451", "Dairy", "Lácteos"],
      ["5462", "Bakeries", "Panaderías"],
      ["5499", "Food Specialty", "Comida especializada"],
      ["5511", "Car Dealers", "Autos nuevos/usados"],
      ["5521", "Used Cars", "Autos usados"],
      ["5532", "Tire Stores", "Llantas"],
      ["5533", "Auto Parts", "Autopartes"],
      ["5541", "Gas Stations", "Gasolineras"],
      ["5542", "Fuel Dispensers", "Bombas automáticas"],
      ["5551", "Boat Dealers", "Barcos"],
      ["5552", "EV Charging", "Carga eléctrica"],
      ["5561", "Trailers", "Remolques"],
      ["5571", "Motorcycles", "Motos"],
      ["5592", "Motor Homes", "RV"],
      ["5598", "Snowmobiles", "Nieve"],
      ["5599", "Vehicle Dealers", "Otros vehículos"],
      ["5611", "Men Clothing", "Ropa hombre"],
      ["5621", "Women Clothing", "Ropa mujer"],
      ["5631", "Women Accessories", "Accesorios"],
      ["5641", "Children Clothing", "Niños"],
      ["5651", "Family Clothing", "Ropa general"],
      ["5655", "Sports Apparel", "Ropa deportiva"],
      ["5661", "Shoe Stores", "Zapatos"],
      ["5681", "Furriers", "Pieles"],
      ["5691", "Clothing Stores", "Ropa general"],
      ["5697", "Tailors", "Sastrería"],
      ["5698", "Wigs", "Pelucas"],
      ["5699", "Apparel Misc", "Ropa varios"],
      ["5712", "Furniture", "Muebles"],
      ["5713", "Floors", "Pisos"],
      ["5714", "Curtains", "Cortinas"],
      ["5718", "Fireplace", "Chimeneas"],
      ["5719", "Home Furnishing", "Decoración"],
      ["5722", "Appliances", "Electrodomésticos"],
      ["5723", "Guns", "Armas"],
      ["5732", "Electronics", "Electrónica"],
      ["5733", "Music Stores", "Instrumentos"],
      ["5734", "Software", "Software"],
      ["5735", "Media Stores", "CDs/DVD"],
      ["5811", "Catering", "Catering"],
      ["5812", "Restaurants", "Restaurantes"],
      ["5813", "Bars", "Bares"],
      ["5814", "Fast Food", "Comida rápida"],
      ["5815", "Digital Media", "Media digital"],
      ["5816", "Digital Games", "Juegos"],
      ["5817", "Digital Apps", "Apps"],
      ["5818", "Large Digital", "Big tech digital"],
      ["5912", "Pharmacy", "Farmacias"],
      ["5921", "Liquor", "Alcohol"],
      ["5931", "Used Goods", "Segunda mano"],
      ["5932", "Antiques", "Antigüedades"],
      ["5933", "Pawn", "Empeños"],
      ["5935", "Salvage", "Chatarra"],
      ["5937", "Reproductions", "Réplicas"],
      ["5940", "Bikes", "Bicicletas"],
      ["5941", "Sports", "Deportes"],
      ["5942", "Books", "Librerías"],
      ["5943", "Office Supplies", "Papelería"],
      ["5944", "Jewelry", "Joyería"],
      ["5945", "Toys", "Juguetes"],
      ["5946", "Cameras", "Fotografía"],
      ["5947", "Gifts", "Regalos"],
      ["5948", "Luggage", "Equipaje"],
      ["5949", "Sewing", "Costura"],
      ["5950", "Glassware", "Cristalería"],
      ["5992", "Florists", "Florerías"],
      ["5993", "Tobacco", "Tabaco"],
      ["5994", "Newsstands", "Periódicos"],
      ["5995", "Pet Shops", "Mascotas"],
      ["5996", "Pools", "Piscinas"],
      ["5997", "Razors", "Afeitadoras"],
      ["5998", "Tents", "Carpas"],
      ["5999", "Misc Retail", "Retail varios"],
      ["6010", "Manual Cash", "Retiros en ventanilla"],
      ["6011", "ATM", "Cajeros automáticos"],
      ["6012", "Bank Services", "Servicios financieros"],
      ["6051", "Crypto/FX", "Cripto/divisas"],
      ["6211", "Brokerage", "Bolsa"],
      ["6300", "Insurance", "Seguros"],
      ["6513", "Real Estate", "Inmobiliario"],
      ["6540", "Stored Value", "Tarjetas prepago"],
      ["7011", "Hotels", "Hoteles"],
      ["7012", "Timeshares", "Tiempo compartido"],
      ["7032", "Camps", "Campamentos"],
      ["7033", "Campgrounds", "Camping"],
      ["7210", "Laundry", "Lavandería"],
      ["7211", "Laundromat", "Autoservicio"],
      ["7216", "Dry Cleaning", "Tintorería"],
      ["7217", "Carpet Cleaning", "Limpieza alfombras"],
      ["7221", "Photography", "Estudios foto"],
      ["7230", "Beauty", "Peluquería"],
      ["7251", "Shoe Repair", "Reparaciones calzado"],
      ["7261", "Funeral", "Funerarias"],
      ["7273", "Dating Services", "Citas"],
      ["7276", "Tax Prep", "Impuestos"],
      ["7277", "Counseling", "Asesoría"],
      ["7278", "Shopping Services", "Personal shopper"],
      ["7296", "Clothing Rental", "Renta ropa"],
      ["7297", "Massage", "Masajes"],
      ["7298", "Spa", "Spa"],
      ["7299", "Personal Services", "Servicios varios"],
      ["7311", "Advertising", "Publicidad"],
      ["7321", "Credit Reporting", "Historial crediticio"],
      ["7322", "Collection Agencies", "Cobranzas"],
      ["7333", "Graphic Design", "Diseño"],
      ["7338", "Copy Services", "Fotocopias"],
      ["7339", "Secretarial", "Servicios oficina"],
      ["7342", "Pest Control", "Fumigación"],
      ["7349", "Cleaning Services", "Limpieza"],
      ["7361", "Employment", "Reclutamiento"],
      ["7372", "IT Services", "Programación"],
      ["7375", "Data Services", "Información"],
      ["7379", "IT Support", "Soporte IT"],
      ["7392", "Consulting", "Consultoría"],
      ["7393", "Security Services", "Seguridad"],
      ["7394", "Equipment Rental", "Alquiler equipos"],
      ["7395", "Photo Development", "Revelado"],
      ["7399", "Business Services", "Servicios varios"],
      ["7512", "Car Rental", "Alquiler autos"],
      ["7513", "Truck Rental", "Camiones"],
      ["7519", "RV Rental", "Vehículos recreativos"],
      ["7523", "Parking", "Estacionamiento"],
      ["7531", "Body Repair", "Reparación carrocería"],
      ["7534", "Tire Repair", "Llantas"],
      ["7535", "Paint", "Pintura autos"],
      ["7538", "Auto Repair", "Mecánica general"],
      ["7542", "Car Wash", "Lavado autos"],
      ["7549", "Towing", "Grúas"],
      ["7800", "Lottery Gov", "Lotería estatal"],
      ["7801", "Online Casino", "Casino online"],
      ["7802", "Horse Racing", "Apuestas caballos"],
      ["7829", "Film Production", "Producción video"],
      ["7832", "Cinemas", "Cines"],
      ["7841", "Video Rental", "Video"],
      ["7911", "Dance Schools", "Danza"],
      ["7922", "Ticket Agencies", "Tickets"],
      ["7929", "Entertainers", "Música en vivo"],
      ["7932", "Billiards", "Billar"],
      ["7933", "Bowling", "Bowling"],
      ["7941", "Sports Clubs", "Deportes profesionales"],
      ["7991", "Tourist Attractions", "Museos"],
      ["7992", "Golf Courses", "Golf público"],
      ["7993", "Game Supplies", "Máquinas juegos"],
      ["7994", "Arcades", "Arcades"],
      ["7995", "Betting", "Apuestas"],
      ["7996", "Amusement Parks", "Parques"],
      ["7997", "Clubs", "Clubes deportivos"],
      ["7998", "Zoos", "Zoológicos"],
      ["7999", "Recreation", "Recreación"],
      ["8011", "Doctors", "Médicos"],
      ["8021", "Dentists", "Dentistas"],
      ["8031", "Osteopaths", "Osteopatía"],
      ["8041", "Chiropractors", "Quiroprácticos"],
      ["8042", "Eye Doctors", "Oftalmología"],
      ["8043", "Opticians", "Óptica"],
      ["8049", "Podiatry", "Podología"],
      ["8050", "Nursing", "Cuidados"],
      ["8062", "Hospitals", "Hospitales"],
      ["8071", "Labs", "Laboratorios"],
      ["8099", "Medical Services", "Salud general"],
      ["8211", "Schools", "Colegios"],
      ["8220", "Universities", "Universidades"],
      ["8241", "Correspondence", "Educación online"],
      ["8244", "Business Schools", "Negocios"],
      ["8249", "Trade Schools", "Técnicos"],
      ["8299", "Education Services", "Educación general"],
      ["8351", "Child Care", "Guarderías"],
      ["8398", "Charities", "ONG"],
      ["8641", "Associations", "Asociaciones"],
      ["8651", "Political", "Políticos"],
      ["8661", "Religious", "Religiosos"],
      ["8675", "Auto Clubs", "Clubes auto"],
      ["8699", "Membership Orgs", "Membresía"],
      ["8734", "Testing Labs", "Laboratorios técnicos"],
      ["8911", "Engineering", "Ingeniería"],
      ["8931", "Accounting", "Contabilidad"],
      ["8999", "Professional Services", "Profesionales"],
      ["9211", "Court Costs", "Tribunales"],
      ["9222", "Fines", "Multas"],
      ["9223", "Bail", "Fianzas"],
      ["9311", "Taxes", "Impuestos"],
      ["9399", "Government", "Gobierno"],
      ["9402", "Postal", "Correos"],
      ["9406", "Lottery Non-US", "Lotería internacional"],
      ["9702", "Emergency Visa", "Emergencias"],
      ["9950", "Intra-company", "Interno empresas"],
    ],
  },
];

export const INICIATIVAS: Iniciativa[] = [
  ["Autorización y reglas", "Smarter Authorization para transacciones de bajo riesgo", "1. Analizar e implementar iniciativas orientadas a optimizar la aprobación de transacciones de bajo riesgo en entornos no presenciales, mediante el uso de modelos analíticos avanzados que permitan transformar potenciales rechazos en aprobaciones controladas. 2. Evaluar el impacto de las mejoras implementadas, considerando la reducción de rechazos innecesarios, la disminución de reintentos transaccionales y la mejora en la experiencia del cliente, especialmente en entornos digitales. 3. Identificar oportunidades para incrementar las tasas de aprobación en transacciones de bajo riesgo, optimizar costos operativos asociados a reintentos y potenciar la generación de ingresos adicionales."],
  ["BINs / Configuración", "Alertas nuevos BIN's", "1. Solicitar la bitácora de creación de nuevos BINES, considerando las funcionalidades de tokenización, su consideración en los ratios de autorización y el uso de herramientas de control de riesgo."],
  ["BINs / Configuración", "Reporte de rangos", "1. Generar un reporte para tener visibilidad de los rangos disponibles por BIN de 8"],
  ["BINs / Configuración", "Implementación y monitoreo de emisión no secuencial de tarjetas", "1. Orquestar las pruebas necesarias para parametrizar la emisión no secuencial en los diferentes tipos de BIN (corporativos y tarjetas de crédito). 2. Implementar el proceso para que las tarjetas, incluyendo aquellas renovadas por vencimiento, sean emitidas bajo lógica no secuencial. 3. Generar reportes que permitan visualizar y monitorear las tarjetas emitidas con numeración no secuencial. 4. Asegurar la correcta configuración y control del proceso, validando su impacto en seguridad, autorización y operación."],
  ["BINs / Configuración", "Optimizar proceso de renovación de tarjetas", "1. Optimizar los procesos internos frente a la renovación de tarjetas."],
  ["Bloqueos", "Cuantificación y análisis de tarjetas bloqueadas con bloqueo 59", "1. Cuantificar los casos y evaluar soluciones, considerando acciones previas a la respuesta con código 59."],
  ["Bloqueos", "Reordenamiento de códigos - TC/TD", "1. Analizar todos los bloqueos internos existentes para tarjetas de débito y crédito. 2. Definir y estructurar los estados de tarjetas con bloqueo, asegurando una clasificación clara y consistente. 3. Realizar la comparativa entre los códigos de bloqueo ISO y categoria actualmente utilizados para validar que responde de forma diferente. 4. Ajustar la asignación de códigos de respuesta para que reflejen correctamente la causal de bloqueo. 5. Identificar a los responsables y gestionar la implementación de los cambios definidos."],
  ["Bloqueos", "Declinaciones bloqueo ATM", "1. Identificar incidencias que generen bloqueos definitivos sobre tarjetas débito tras intentos fallidos de autenticación por ingreso incorrecto de clave en ATM. 2. Definir un plan de acción para optimizar la gestión de estas declinaciones, reemplazando bloqueos definitivos por bloqueos temporales para reducir el impacto en el tarjetahabiente."],
  ["Bloqueos", "Homologación de códigos de respuesta crédito / debito", "1. Analizar el origen y comportamiento de las diferentes declinaciones en tarjetas de crédito. 2. Asignar a cada declinación el código de respuesta ISO correspondiente, de acuerdo con las especificaciones y estándares definidos. 3. Mejorar la trazabilidad de las transacciones, la interpretación de las causales de rechazo y la gestión operativa y transaccional."],
  ["Bloqueos", "Optimizar declinación bloqueo en Primer Uso", "1. Optimizar el proceso de activación de tarjetas de nueva emisión."],
  ["Bloqueos", "Cancelación de tarjetas sin aprobaciones", "1. Depurar el portafolio de clientes que no generan valor."],
  ["Bloqueos / Políticas de riesgo", "Aumento de límites para declinaciones por actuales vencidos", "1. Analizar las políticas de bloqueo implementadas por el emisor, las cuales generaban el bloqueo automático de las tarjetas desde el primer día de mora posterior a la fecha límite de pago. 2. A partir del diagnóstico, se propusieron optimizaciones orientadas a flexibilizar dicha restricción, 3. El objetivo es reducir declinaciones innecesarias, mejorar la experiencia del tarjetahabiente y aumentar las tasas de autorización y facturación."],
  ["Bloqueos / VSPS", "Optimización de declinaciones por tarjetas bloqueadas/boletinadas en VSPS", "1. Analizar e implementar acciones orientadas a reducir la participación de declinaciones asociadas a tarjetas bloqueadas y boletinadas. 2. Identificar oportunidades de mejora en los procesos y configuraciones actuales. 3. Incorporar credenciales en VSPS, optimizar los tiempos y políticas de bloqueo, y homologar los códigos de respuesta. 4. Medir impacto en tasas de autorización y ajustar continuamente para mejorar la experiencia del tarjetahabiente."],
  ["Botonera", "Migración a push a la botonera", "1. Compartir el impacto del código 93 con el equipo responsable de gestión de gatillos. 2. Validar la disponibilidad del push en ambiente productivo. 3. Confirmar que se cuenta con la estructura necesaria para explotar la información y definir el tipo de comunicación a enviar."],
  ["Botonera", "GAP's con la botonera", "1. Identificar los rechazos por código 93 en función del modo de entrada reportado por comercios y adquirientes. 2. Implementar notificaciones mediante push y correo. 3. Coordinar una reunión para revisar el paquete de VPLUS e identificar la configuración asociada a cada tipo de rechazo."],
  ["Botonera", "Interfaz API Push Tarjeta de Crédito", "1. Generar una Interfaz API para Push para notificaciones de botoneras o CVV mediante el App"],
  ["Botonera", "DeepLink - Campañas Educativas", "1. Generar un deeplink para potenciar campañas educativas de botones y CVV dinámico"],
  ["Comunicaciones", "Notificación de declinaciones", "1. Implementar notificaciones transaccionales en tiempo real para informar a los clientes sobre el resultado de sus solicitudes de autorización. 2. Permitir la visualización inmediata de si una transacción fue aprobada o declinada, incluyendo las posibles causas asociadas."],
  ["Comunicaciones", "Notificación de recurrencias", "1. Desarrollar comunicaciones anticipadas para notificar a los clientes sobre futuras transacciones recurrentes. 2. Buscando reducir declinaciones por fondos insuficientes Y mejorar la experiencia transaccional mediante acciones preventivas oportunas."],
  ["Cumplimiento / Multas", "Optimización de multas", "1. Analizar las incidencias y desviaciones que generan multas por incumplimiento de mandatos de la marca. 2. Identificar oportunidades de mejora asociadas a dichas incidencias. 3. Implementar acciones correctivas orientadas al cumplimiento de estándares establecidos. 4. Asegurar el cumplimiento de estándares y minimizar riesgos operativos y financieros."],
  ["Cumplimiento / Visa", "Cartas waiver", "1. Cerrar las cartas de compromiso asociadas a autorización parcial y autorización incremental. 2. Gestionar el envío de las cartas de compromiso hacia el nuevo autorizador. 3. Atender las observaciones identificadas y gestionarlas en el corto plazo."],
  ["CVV Dinámico", "Implementación y evaluación de CVV dinámico", "1. Validar la factibilidad de implementación de la iniciativa. 2. Reunirse con el equipo de desarrollo para evaluar la viabilidad. 3. Estimar tiempos de implementación y definir alternativas de solución. 4. Identificar el alcance de lo que sí es posible implementar. 5. Analizar el impacto de las mejoras de CVV dinámico en la autorización. 6. Esperar las respuestas del equipo de CVV para revisar dicho impacto."],
  ["CVV Dinámico", "Migración CVV Dinámico", "1. Orquestar la estrategia de migración al CVV Dinámico"],
  ["CVV Dinámico", "Plan educativo CVV Dinámico", "1. Ejecutar el plan educativo asociado a CVV dinámico."],
  ["CVV Dinámico", "Whitelist CVV dinámico", "1. Generar un Whitelist para utilizar exclusivamente el CVV Dinámico en BINes que aún no tienen la convivencia apagada"],
  ["CVV Dinámico", "Blacklist CVV Dinámico", "1. Generar un Blacklist para que los clientes de BINes con CVV impreso apagado puedan utilizar la tarjeta como si estuvieran en convivencia"],
  ["Diagnóstico", "Diagnóstico tarjeta de crédito", "1. Realizar un diagnóstico integral del procesamiento de autorizaciones en tarjetas de crédito, entendiendo el funcionamiento de los sistemas. 2. Identificar incidencias, oportunidades de optimización y mejoras operativas. 3. Contribuir a incrementar el desempeño del producto, la tasa de aprobación y la experiencia del cliente."],
  ["Fondos insuficientes / Comunicación", "Comunicación fondos insuficientes", "1. Desarrollar comunicación para aviso de cuando un cliente se queda al 80% de línea"],
  ["Fondos insuficientes / Comunicación", "Notificaciones preventivas saldo/línea", "1. Generar alertas preventivas de saldo disponible para reducir reintentos"],
  ["Fondos insuficientes / Comunicación", "Notificar fechas de pago TC", "1. Notificar eventos clave de manera proactiva, incluyendo pagos, aplicación de crédito (CR) y depósitos (DB)."],
  ["Fondos insuficientes / Comunicación", "Realizar notificaciones proactivas", "1. Analizar los mensajes existentes de SMS, push y otros canales para tarjetas de crédito (TC) y tarjetas de débito (TD). 2. Estandarizar los mensajes para asegurar consistencia en la comunicación."],
  ["Fondos insuficientes / Comunicación", "Notificar de declinaciones", "1. Optimizar los mensajes de SMS, push y correo. 2. Unificar la estructura de comunicación para asegurar uniformidad, educar al cliente y enviar recordatorios sobre recurrencias, límites y otros eventos relevantes."],
  ["Fondos insuficientes / Comunicación", "Implementar notificaciones proactivas", "1. Optimizar los mensajes de SMS, push y correo unificando la estructura para tener uniformidad e incentivar una acción del cliente"],
  ["Fondos insuficientes / Overlimit", "Implementación y optimización de políticas de Overlimit", "1. Revisar la factibilidad de implementar esquemas de overlimit, incluyendo la aceptación de transacciones específicas (como recurrencias) en casos de fondos insuficientes. 2. Implementar un modelo de Overlimit que permita la habilitación de cupos adicionales sobre el límite de la tarjeta. 3. Segmentar clientes para identificar aquellos con buen comportamiento y habilitar un porcentaje adicional dentro de su cupo asignado. 4. Permitir la aprobación de transacciones que puedan ser declinadas por fondos insuficientes, mediante la configuración de parámetros específicos."],
  ["Fondos insuficientes / Overlimit", "Reducción plazo cobrador de mora", "1. Reducir los días de cobro automático de mora (de 2 a 1 día)"],
  ["Fondos insuficientes / Overlimit", "Mejora de políticas sobregiro - Riesgos", "1. Realizar challenge al equipo de riesgos de políticas de sobregiro"],
  ["Fondos insuficientes / Overlimit", "Alternativas para disminuir declinaciones por FI en TD", "1. Disminuir declinaciones por fondos insuficientes"],
  ["Fraude", "Elaborar Kickoff de Fraude", "1. Elaborar mesas de trabajo con el equipo de RNF / Fraudes para analizar la presencia de ataques."],
  ["Fraude", "Mesas de trabajo – Prevención de fraude", "1. Orquestar mesas de trabajo con fraudes para realizar la revisión y validación de reglas existentes."],
  ["Fraude", "Reemisión de tarjetas comprometidas", "1. Reemitir tarjetas comprometidas utilizando la funcionalidad de emisión no secuencial."],
  ["Fraude", "Nuevo proceso emisión TC", "1. Modificar el proceso de emisión de tarjetas para evitar la emisión de tarjetas previamente atacadas."],
  ["Gobernanza / Campañas", "Revisar todas las campañas", "1. Elaborar un resumen consolidado de todas las campañas y definir responsables para cada una. 2. Gestionar la comunicación con todos los involucrados, incluyendo el envío de convocatorias, actas y seguimiento de fechas. 3. Revisar el feedback en conjunto con el equipo responsable de cada campaña. 4. Evaluar el impacto de las campañas mediante el análisis de indicadores como el ratio de desempeño."],
  ["Gobernanza / Campañas", "Campañas educativas", "1. Generar campañas educativas para reducir declinaciones por fondos insuficientes o botón general, internet, y compras en el extranjero"],
  ["Gobernanza / Campañas", "Alineamiento de estrategias de autorización en eventos de alto impacto", "1. Identificar eventos o periodos de alto impacto que puedan influir en el comportamiento transaccional. 2. Definir las acciones que debe implementar el equipo de autorizaciones para optimizar la tasa de autorización durante dichos periodos."],
  ["Gobernanza / Campañas", "Implementar comité de proyecto", "1. Implementar un gobierno de autorizaciones orientado al análisis de la tasa de autorizacipon, la identificación de mejoras y la definición de iniciativas que optimicen el procesos autorizaciones"],
  ["Gobernanza / Campañas", "Conformar comisión de autorizaciones", "1. Se tiene como objetivo conformar un equipo integrar enfocado a discutir actividades y/o propuestas referentes a temas de autorizaciones"],
  ["Gobernanza / Campañas", "Optimizar el equipo de autorizaciones", "1. Capacitar al equipo de autorizaciones sobre procesos relacionados con análisis, objetivos y temas relevantes de las iniciativas"],
  ["Gobernanza / Campañas", "Actividades preventivas para evitar declinaciones durante el mundial (Dom –XB)", "1. Definir las acciones a implementar por el equipo de autorizaciones para mejorar la tasa de autorización durante periodos de alta demanda transaccional, como las fechas del mundial."],
  ["Límites", "Declinaciones por error en límite", "1. Desarrollar e implementar iniciativas que permitan a los clientes administrar 2. Ajustar de manera más eficiente sus límites personalizados 3. Minimizando las declinaciones por límite insuficiente y potenciando la generación de transacciones aprobadas."],
  ["Límites", "Aumento límites de monto", "1. Implementar ajustes en el límite general del producto para transacciones Card Present (CP) y Card Not Present (CNP). 2. Ampliar la experiencia transaccional de los clientes, reducir fricciones operativas, incrementar la facturación y mejorar la tasa de aprobación."],
  ["Límites", "Aumento límites de usos", "1. Analizar el impacto de las reglas que restringen la cantidad de usos de la tarjeta. 2. Identificar e implementar oportunidades de optimización. 3. Mejorar la experiencia del tarjetahabiente, incrementar la tasa de autorización y potenciar la facturación e ingresos."],
  ["Límites", "Optimización declinaciones de avances por número de usos", "1. Analizar las restricciones asociadas al número de avances permitidos por tarjetahabiente. 2. Identificar oportunidades para incrementar los límites de uso. 3. Reducir declinaciones innecesarias, mejorar la experiencia del cliente y aumentar el volumen transaccional y las tasas de autorización."],
  ["Líneas de Crédito", "Incremento de línea", "1. Generar y comunicar los leads de ampliación de línea a los clientes definidos. 2. Identificar incidencias en el proceso de aceptación del incremento de línea. 3. Gestionar la implementación de mejoras (fix) en el ambiente correspondiente. 4. Promover un esquema de revisión y challenge continuo para el incremento de líneas."],
  ["Listas Negras", "Listas Negras", "1. Armar un proceso de cómo se va a hacer todos los meses (que día, solicitud, etc.)"],
  ["MAR y Reintentos", "MAR", "1. Cerrar seguimiento del MAR y automatizarlo"],
  ["MAR y Reintentos", "MAR 2.0", "1. Armar un deep dive en SQL para entender primero fondos insuficientes"],
  ["MAR y Reintentos", "MAR ampliar el análisis de reintentos 51 y 59", "1. Solicitar el código interno para analizar su composición. 2. Revisar tarjetas con menos de 40 reintentos dentro del mes para VSPS. 3. Solicitar el código de establecimiento de los comercios con mayor rechazo de reintentos."],
  ["MAR y Reintentos", "MAR – Seguimiento Planes de Acción", "1. Actualizar y monitorear el desempeño en la penalidad MAR"],
  ["MAR y Reintentos", "Crear un plan de acción MAR", "1. Generar un plan de acción para reducir las declinaciones. 2. Alcanzar los objetivos de tasa de autorización para BINes específicos y evitar multas."],
  ["MAR y Reintentos", "Seguimiento y prevención de multas por MAR", "1. Analizar las tasas de autorización frente al programa de la franquicia identificando oportunidades de mejora hasta llegar a al porcentaje de cumplimiento mínima requerida"],
  ["Monitoreo", "Implementar mejoras a los tableros de monitoreo", "1. Mejorar los tableros de autorización, incorporando filtros en las consultas para visualizar un enfoque 360 de las autorizaciones."],
  ["Monitoreo", "Monitorear el desempeño mediante Visa Processing Performance Monitor (VPPM)", "1. Capacitación al equipo de autorizaciones para el uso de la plataforma"],
  ["Monitoreo", "Implementar de tableros de monitoreo", "1. Definir e implementar dashboards para el seguimiento de KPI del equipo de autorizaciones de forma amigable y automática. 2. Acompañar la implementación de tableros de autorizaciones para monitorear el comportamiento transaccional. 3. Analizar el comportamiento transaccional a partir de los indicadores definidos. 4. Identificar tendencias, desviaciones y causas raíz, proponiendo soluciones acordes. 5. Facilitar la toma de decisiones basada en indicadores clave de desempeño y oportunidades de optimización."],
  ["Monitoreo", "Gestionar el proceso de monitoreo", "1. Analizar el comportamiento transaccional. 2. Identificar la causa raíz de desviaciones y proponer soluciones acordes."],
  ["Parámetros de Tarjeta", "Modificación de parametro tarjeta empresarial", "1. Evaluar el impacto del cambio asociado al BIN empresarial"],
  ["Parámetros de Tarjeta", "Definir nuevos límites", "1. Analizar los límites actuales y su comportamiento, considerando las tasas de declinación. 2. Redefinir los límites en función del uso del producto y los resultados del análisis. 3. Modificar los parámetros de los límites generales de uso y monto dentro del autorizador."],
  ["Parámetros de Tarjeta", "Segregar de limites CP y CNP", "1. Permitir la diferenciación entre límites de venta Card Present (CP) y Card Not Present (CNP), aplicable cuando existe un solo límite general."],
  ["Procesador", "Soporte en la masificación del nuevo procesador", "1. Acompañar el proceso de estabilización y masificación del nuevo procesador de tarjeta débito. 2. Implementar esquemas de monitoreo transaccional. 3. Identificar incidencias operativas. 4. Brindar soporte en la definición e implementación de soluciones para garantizar la continuidad y estabilidad del servicio."],
  ["Proyectos", "Proyecto VCX", "1. Compartir la calculadora del proyecto. 2. Gestionar el requerimiento de contratación de perfiles LT y PM. 3. Solicitar y revisar los perfiles definidos para la asignación de desarrolladores."],
  ["Proyectos", "Caso de negocio", "1. Definir y compartir la propuesta del rumbo de la consultoría. 2. Mostrar los posibles resultados asociados a la implementación de las iniciativas."],
  ["Proyectos", "Revisión y Aprobación nuevo caso de negocio", "1. Identificar los valores a recuperar con la implementación de las iniciativas, incluyendo recuperación de transacciones, facturación, disminución de declinaciones, impacto en la tasa de autorización, reducción de costos de procesamiento y aumento en utilidades."],
  ["QR / Ecommerce", "Identificación de operaciones QR", "1. Analizar las transacciones Card Not Present para identificar las operaciones correspondientes a QR. 2. Definir el criterio de identificación de operaciones QR, considerando campos como CVV en blanco. 3. Canalizar estas operaciones a través del proceso de reclamos correspondiente"],
  ["Reclamos / ONR", "Revisión evolutivo ONR", "1. Analizar el incremento de ONR en tarjetas de débito (TD). 2. Realizar un análisis de reclamos para identificar su origen, distribución y características."],
  ["Autorización y reglas", "Revisión de reglas de MTT", "1. Analizar las transacciones aprobadas por reglas. 2. Atender alertas asociadas a posibles casos de fraude y riesgos no financieros en coordinación con el equipo de RNF / Fraudes. 3. Realizar una corrida de las transacciones aprobadas para validar la presencia de fraude. 4. Validar las reglas aplicadas en la autorización, incluyendo controles como validación de saldo."],
  ["Autorización y reglas", "Revisión de reglas de negocio", "1. Consolidar el listado de reglas de negocio existentes. 2. Analizar cada regla de forma individual para validar su uso y efectividad. 3. Gestionar la comunicación con el equipo de POS para solicitar el estado de las mejoras. 4. Implementar la solución para identificar si la operación corresponde a una transacción con clave PIN."],
  ["Autorización y reglas", "Revisión de reglas Visa Direct", "1. Revisar el listado de reglas para OCT/AFT y cuantificar el impacto de cada una. 2. Analizar la información disponible en lake o VAP para identificar oportunidades de mejora. 3. Definir acciones de optimización a partir del análisis realizado."],
  ["Autorización y reglas", "Mejora política de mora – Riesgos", "1. Monitorear la ejecución de mejoras en las políticas de autorización asociadas a declinaciones por mora."],
  ["Autorización y reglas", "Optimización declinaciones operación no permitida en avances", "1. Analizar las reglas de negocio que restringen la cantidad de avances vigentes permitidos por tarjeta. 2. Identificar el impacto de estas reglas en declinaciones, incluso en casos donde existe cupo disponible. 3. Evaluar escenarios donde los avances diferidos limitan la capacidad de realizar nuevas transacciones. 4. Identificar oportunidades de optimización para flexibilizar las reglas, reducir fricciones transaccionales y mejorar la experiencia del cliente, la tasa de aprobación y el uso del producto."],
  ["Autorización y reglas", "Depuración de reglas monto / usos", "1. Analizar las reglas de negocio que restringen los montos y el número de usos en tarjetas de crédito en determinados comercios y categorías MCC (Merchant Category Code). 2. Identificar oportunidades de optimización y definir ajustes para flexibilizar dichas restricciones. 3. Incrementar la facturación, mejorar las tasas de autorización y reducir declinaciones innecesarias."],
  ["Autorización y reglas", "Definir metas de autorización", "1. Definir la tasa de autorización para portafolio débito y crédito, considerando el estado de las tasas al inicio de la consultoría."],
  ["Autorización y reglas", "Desactivar el modo de entrada de banda magnética", "1. Desactivar el modo de entrada banda magnética para Ecuador y Estados Unidos"],
  ["Autorización y reglas", "Propuesta forzado de cuenta para transacciones con tarjeta", "1. Implementar una regla de negocio para aprobar transacciones que actualmente son declinadas bajo determinadas condiciones o por ingreso incorrecto del número de cuenta."],
  ["Autorización y reglas", "Propuesta CVV2 en transacciones COF", "1. Implementar una regla de negocio que permita aprobar las transacciones COF sin la validación del CVV2"],
  ["Autorización y reglas", "Definir metas de autorizaciones", "1.Establecer un objetivo de tasa de autorización apalancado en iniciativas y optimizaciones."],
  ["Autorización y reglas", "Excluir validación de caducidad en recurrencias tarjeta débito / Credito", "1. Permitir que las transacciones de recurrencia continúen su flujo transaccional aun cuando el plástico de la tarjeta se haya vencido, manteniendo la validación de seguridad de la fecha de vencimiento."],
  ["Autorización y reglas", "Revisión de parámetros de STIP", "1. Identificar y analizar configuraciones relacionadas con el procesamiento de Stand-in actual, con el objetivo de optimizar estos parámetros de acuerdo al comportamiento transaccional."],
  ["Autorización y reglas", "Forzar cuenta TD – mala selección de cuenta", "Mitigar declinaciones originadas por una incorrecta selección de producto en el momento de la compra, aplicable a débito, crédito, retiros y avances en Card Present (CP)."],
  ["Seguridad", "Modelo de gobierno para administración de llave de seguridad", "1. Definir un modelo de gobierno y una estructura operativa para la administración de llaves de seguridad, estableciendo roles, responsabilidades, controles y procesos orientados a fortalecer la seguridad. 2. Garantizar el cumplimiento de estándares y mitigar riesgos asociados a la gestión criptográfica."],
  ["Seguridad", "Definición de meta/objetivo", "1. Definir un indicador objetivo de autorizaciones para alinear equipos y terceros en torno a métricas claras."],
  ["Seguridad", "Fortalecer la estructura de autorización", "2. Robustecer el equipo de autorizaciones mediante la adopción de mejores prácticas y la centralización de la gestión en Producto."],
  ["Seguridad", "Notificar las transacciones negadas", "1. Incluir transacciones denegadas en notificaciones para mejorar la comunicación con clientes"],
  ["Seguridad", "Acciones operativas fondos insuficientes", "1. Depurar cuentas de manera periódica para mejorar la precisión de rechazos y reducir reintentos."],
  ["Seguridad", "Reordenamiento de códigos - TD", "1. Mejorar la información al cliente sobre disponibilidad de fondos y rechazos por insuficiencia."],
  ["Seguridad", "Gestión Límites Transaccionales", "1. Acelerar la implementación y segmentación de nuevos límites en transacciones débito."],
  ["Seguridad", "Homologar Rechazos Sospecha de Fraude", "1. Reducir rechazos por fraude mediante colaboración con el equipo de Prevención en la gestión de herramientas y causales."],
  ["Seguridad", "Gestión de Bloqueos", "1. Optimizar la clasificación de bloqueos para evitar intentos innecesarios por parte de los comercios."],
  ["Seguridad", "Homologación de Causales", "1. Mejorar los códigos de rechazo en coordinación con Fiserv para reducir reintentos de comercios."],
  ["Seguridad", "Mapeo flujo E2E de procesamiento", "1. Documentar el flujo transaccional combinando visión operativa y técnica"],
  ["Seguridad", "Automatización y construcción de tableros y reportes de indicadores", "1. Construir un tablero dinámico para monitorear cifras de autorizaciones en comités. 2. Automatizar reportes transaccionales para mejorar la calidad y oportunidad de los datos."],
  ["Seguridad", "Completitud de Información en los Sistemas", "1. Integrar datos de Producto y Operaciones para un análisis más completo de tendencias"],
  ["Seguridad", "Complemento Indicadores Gestión Transaccional", "1. Complementar indicadores de autorización con visión estratégica y táctica"],
  ["Seguridad", "Proceso de aprovisionamiento", "1. Organizar la información para generar estrategias para mejorar los niveles de aprovisionamiento"],
  ["Seguridad", "Comparativo fuentes de información", "1. Análisis entre las funetes del banco y Visa para comprender las diferencias identificadas en la información generada"],
  ["Stand-In / Continuidad", "Optimización del standin Visa", "1. Analizar las configuraciones del servicio Stand-In en los sistemas de Visa, 2. Identificando oportunidades de optimización que permitan mejorar el desempeño del proceso de respaldo 3. Incrementar la continuidad operativa 4. Reducir el impacto de posibles indisponibilidades en los sistemas del emisor."],
  ["Tokenización", "Tokenización", "1. Revisar el indicador de rechazo 96 (error de sistema), asociado a card-eligibility."],
  ["Tokenización", "Sincronización Tokens Marca", "1. Realizar seguimiento a la sincronización de tokens"],
  ["Tokenización", "Implementar el proceso ABU (Tarjeta expirada)", "1. Implementar el envío de credenciales a través de ABU y/o presentar la propuesta de implementación de VAU."],
  ["Tokenización", "Actualizar tarjetas en bóveda de tokenización", "1. Realizar la depuración de tarjetas y tokens vencidos en el módulo de TLMC (módulo de gestión del ciclo de vida del token)."],
  ["Tokenización", "Revisar proceso de actualización de credenciales por VAU", "1. Incentivar el uso adecuado del manejo del ciclo de vida del token y de las bóvedas."],
  ["Transacciones Especiales (AFT/OCT)", "Transacciones AFT", "1. Acompañar el proceso de implementación y habilitación de transacciones AFT (Account Funding Transactions). 2. Asegurar una integración eficiente, alineada con los requerimientos operativos y regulatorios definidos para este tipo de transacciones."],
  ["VSPS", "Inclusión credenciales VSPS", "1. Acompañar la definición e identificación de credenciales susceptibles de ser marcadas en VSPS. 2. Optimizar el procesamiento transaccional, reducir la recepción de declinaciones no deseadas y disminuir costos asociados al procesamiento de transacciones rechazadas. 3. Mejorar las tasas de autorización y la eficiencia operativa."],
  ["VSPS", "Catch & Release", "1. Implementar una estrategia de bloqueos y desbloqueos dinámicos en VSPS orientada a restringir de manera temprana credenciales con potencial de generar múltiples declinaciones. 2. Evitar impactos negativos en las tasas de autorización. 3. Contemplar bloqueos preventivos de corta duración y procesos automáticos de desbloqueo en un periodo aproximado de un mes. 4. Reducir declinaciones futuras, optimizar el desempeño transaccional y minimizar afectaciones sobre credenciales legítimas."],
  ["VSPS", "Monitoreo de VSPS", "1. Evaluar VSPS para reintentos menores a 40 con fondos. 2. Realizar un nuevo análisis de VSPS en coordinación con el equipo correspondiente."],
  ["VSPS", "Uso de VSPS", "1. Uso de la herramienta Visa Stop Payments (VSPS) para reducir declinaciones para pagos recurrentes"],
  ["VSPS", "Incluir credenciales en Visa Stop Payment Service (VSPS) tarjeta restringida", "1. Realizar análisis de las tarjetas restringidas para su carga en VSPS. 2. Reducir los reintentos rechazados que generan costos."],
  ["VSPS", "Incluir credenciales en Visa Stop Payment Service (VSPS)", "1. Incentivar el uso de la herramienta que permita contener los reintentos de transacciones declinadas. 2. Basar la selección de instrucciones en un análisis que permita priorizar aquellas de mayor valor."],
];

export const CONCEPTOS: string[] = ["Autorización y reglas", "BINs / Configuración", "Bloqueos", "Bloqueos / Políticas de riesgo", "Bloqueos / VSPS", "Botonera", "CVV Dinámico", "Comunicaciones", "Cumplimiento / Multas", "Cumplimiento / Visa", "Diagnóstico", "Fondos insuficientes / Comunicación", "Fondos insuficientes / Overlimit", "Fraude", "Gobernanza / Campañas", "Listas Negras", "Límites", "Líneas de Crédito", "MAR y Reintentos", "Monitoreo", "Parámetros de Tarjeta", "Procesador", "Proyectos", "QR / Ecommerce", "Reclamos / ONR", "Seguridad", "Stand-In / Continuidad", "Tokenización", "Transacciones Especiales (AFT/OCT)", "VSPS"];

/** Fila del diccionario ya resuelta con su contexto de seccion. */
export type Fila = { sheet: string; sec: string; pri: string; hdr: string[]; row: string[] };

/** Indice codigo -> filas. Un mismo codigo puede existir en varias sub-tablas
 *  (ej. "1" en Category y en CAVV), por eso el valor es un array. */
const IDX = new Map<string, Fila[]>();
for (const s of SECCIONES) {
  for (const row of s.rows) {
    const k = row[0].toLowerCase();
    const f: Fila = { sheet: s.sheet, sec: s.sec, pri: s.pri, hdr: s.hdr, row };
    const cur = IDX.get(k);
    if (cur) cur.push(f);
    else IDX.set(k, [f]);
  }
}

/** Lookup exacto O(1) por codigo. */
export function lookupCodigo(cod: string): Fila[] {
  return IDX.get(cod.trim().toLowerCase()) ?? [];
}

export const TOTAL_REGISTROS = SECCIONES.reduce((n, s) => n + s.rows.length, 0);
export const TOTAL_SECCIONES = SECCIONES.length;
